// 路径: prototype/app/Showcase.jsx 版本: 1.5.0
"use client";

import { useEffect, useMemo, useState, useCallback, useRef } from "react";

// 界面文案双语映射（UI 文案，非业务数据）
const UI = {
  zh: {
    all: "全部",
    skillsUnit: "个技能",
    catsUnit: "个分类",
    viewRepo: "查看仓库",
    install: "安装指南",
    searchPh: "搜索技能名称、描述或分类…",
    searchLabel: "搜索技能",
    toggleTheme: "切换主题",
    toggleLang: "Switch to English",
    clear: "清除筛选",
    viewGrid: "网格视图",
    viewList: "列表视图",
    showing: "显示",
    of: " / ",
    emptyTitle: "没有匹配的技能",
    emptyDesc: "换个关键词或分类试试。",
    maintained: "共 ",
    by: " 个技能 · 由 ",
    maintainedBy: " 维护 · 生成于 ",
    footerNote: " 的静态展示，由 Next.js 构建、",
    footerNote2: " 自动生成数据。许可证：MIT。",
    viewSkill: "在仓库中查看 SKILL.md →",
    close: "关闭",
    subtitle: "面向开发、设计、测试、DevOps、Agent 工程及各行业领域的 AI 技能集合",
    installHint: "使用 skills-manager 安装",
  },
  en: {
    all: "All",
    skillsUnit: "skills",
    catsUnit: "categories",
    viewRepo: "View repo",
    install: "Install guide",
    searchPh: "Search by name, description or category…",
    searchLabel: "Search skills",
    toggleTheme: "Toggle theme",
    toggleLang: "切换到中文",
    clear: "Clear filters",
    viewGrid: "Grid view",
    viewList: "List view",
    showing: "Showing",
    of: " / ",
    emptyTitle: "No matching skills",
    emptyDesc: "Try another keyword or category.",
    maintained: "Total ",
    by: " skills · maintained by ",
    maintainedBy: " · generated on ",
    footerNote: " static showcase, built with Next.js and generated by ",
    footerNote2: ". License: MIT.",
    viewSkill: "View SKILL.md in repo →",
    close: "Close",
    subtitle:
      "A collection of AI skills for development, design, testing, DevOps, agent engineering and industry domains",
    installHint: "Install with skills-manager",
  },
};

// 图标集合（内联 SVG，无外部依赖）
const Icon = {
  search: (
    <svg className="search-icon" viewBox="0 0 24 24" width="18" height="18" aria-hidden="true">
      <path fill="currentColor" d="M15.5 14h-.79l-.28-.27a6.5 6.5 0 1 0-.7.7l.27.28v.79l5 4.99L20.49 19l-4.99-5Zm-6 0A4.5 4.5 0 1 1 14 9.5 4.5 4.5 0 0 1 9.5 14Z" />
    </svg>
  ),
  sun: (
    <svg viewBox="0 0 24 24" width="20" height="20" fill="currentColor" aria-hidden="true">
      <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79Z" />
    </svg>
  ),
  moon: (
    <svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
      <circle cx="12" cy="12" r="4" />
      <path d="M12 2v2M12 20v2M2 12h2M20 12h2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4" />
    </svg>
  ),
  grid: (
    <svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
      <rect x="3" y="3" width="7" height="7" rx="1.5" /><rect x="14" y="3" width="7" height="7" rx="1.5" />
      <rect x="3" y="14" width="7" height="7" rx="1.5" /><rect x="14" y="14" width="7" height="7" rx="1.5" />
    </svg>
  ),
  list: (
    <svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
      <line x1="8" y1="6" x2="21" y2="6" /><line x1="8" y1="12" x2="21" y2="12" /><line x1="8" y1="18" x2="21" y2="18" />
      <circle cx="3.5" cy="6" r="1.2" fill="currentColor" /><circle cx="3.5" cy="12" r="1.2" fill="currentColor" /><circle cx="3.5" cy="18" r="1.2" fill="currentColor" />
    </svg>
  ),
  empty: (
    <svg viewBox="0 0 24 24" width="40" height="40" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
      <circle cx="11" cy="11" r="7" /><line x1="21" y1="21" x2="16.65" y2="16.65" />
      <line x1="8" y1="11" x2="14" y2="11" />
    </svg>
  ),
};

export default function Showcase({ data }) {
  const { meta, categories, skills } = data;
  const [activeCat, setActiveCat] = useState("全部");
  const [query, setQuery] = useState("");
  const [view, setView] = useState("grid");
  const [modal, setModal] = useState(null);
  const [theme, setTheme] = useState("light");
  const [scrolled, setScrolled] = useState(false);
  const [lang, setLang] = useState(() => {
    if (typeof document === "undefined") return "zh";
    const stored = document.documentElement.getAttribute("data-lang");
    if (stored === "en" || stored === "zh") return stored;
    return (navigator.language || "").toLowerCase().startsWith("en") ? "en" : "zh";
  });
  const toolbarRef = useRef(null);

  useEffect(() => {
    const cur =
      document.documentElement.getAttribute("data-theme") ||
      (window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light");
    setTheme(cur);
  }, []);

  // Toolbar 滚动态
  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 8);
    onScroll();
    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  const toggleTheme = () => {
    const next = theme === "dark" ? "light" : "dark";
    setTheme(next);
    document.documentElement.setAttribute("data-theme", next);
    try { localStorage.setItem("theme", next); } catch (e) { /* 忽略 */ }
  };

  const toggleLang = () => {
    const next = lang === "en" ? "zh" : "en";
    setLang(next);
    document.documentElement.setAttribute("data-lang", next);
    document.documentElement.lang = next === "en" ? "en" : "zh-CN";
    try { localStorage.setItem("lang", next); } catch (e) { /* 忽略 */ }
  };

  const t = UI[lang];
  const catEnMap = useMemo(
    () => Object.fromEntries((data.categories || []).map((c) => [c.name, c.en || c.name])),
    [data.categories]
  );
  const catName = (name) => (lang === "en" ? catEnMap[name] || name : name);

  const catList = useMemo(
    () => [{ name: "全部", count: skills.length }].concat(categories),
    [categories, skills.length]
  );

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    return skills.filter((s) => {
      if (activeCat !== "全部" && s.category !== activeCat) return false;
      if (!q) return true;
      const hay = [s.name, s.zh_desc, s.en_desc, s.category].join(" ").toLowerCase();
      return hay.indexOf(q) !== -1;
    });
  }, [skills, activeCat, query]);

  const openModal = useCallback((s) => setModal(s), []);
  const closeModal = useCallback(() => setModal(null), []);

  useEffect(() => {
    if (!modal) return;
    const onKey = (e) => { if (e.key === "Escape") closeModal(); };
    document.addEventListener("keydown", onKey);
    document.body.style.overflow = "hidden";
    return () => {
      document.removeEventListener("keydown", onKey);
      document.body.style.overflow = "";
    };
  }, [modal, closeModal]);

  const tagHtml = (s) => (
    <>
      <span className={"tag" + (s.has_scripts ? " has" : "")}>scripts</span>
      <span className={"tag" + (s.has_references ? " has" : "")}>references</span>
      <span className={"tag" + (s.has_assets ? " has" : "")}>assets</span>
    </>
  );

  const repoBase = (meta.repo || "").replace(/\/$/, "");

  return (
    <>
      <header className="hero" id="hero">
        <div className="hero-inner">
          <div className="badge">AGENT SKILLS HUB</div>
          <h1>{meta.title}</h1>
          <p className="subtitle">{t.subtitle}</p>
          <div className="stats" role="group" aria-label={t.skillsUnit + " / " + t.catsUnit}>
            <div className="stat">
              <div className="stat-num">{meta.count}</div>
              <div className="stat-label">{t.skillsUnit}</div>
            </div>
            <div className="stat">
              <div className="stat-num">{categories.length}</div>
              <div className="stat-label">{t.catsUnit}</div>
            </div>
          </div>
          <div className="cta">
            <a className="btn btn-primary" href={meta.repo} target="_blank" rel="noopener">
              {t.viewRepo}
            </a>
            <a
              className="btn btn-ghost"
              href="https://github.com/xingkongliang/skills-manager"
              target="_blank"
              rel="noopener"
            >
              {t.install}
            </a>
          </div>
        </div>
      </header>

      <main className="container">
        <section
          className={"toolbar" + (scrolled ? " scrolled" : "")}
          id="toolbar"
          ref={toolbarRef}
        >
          <div className="toolbar-top">
            <div className="search-wrap">
              {Icon.search}
              <input
                id="search"
                type="search"
                placeholder={t.searchPh}
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                autoComplete="off"
                aria-label={t.searchLabel}
              />
            </div>
            <button
              className="icon-btn"
              onClick={toggleLang}
              aria-label={t.toggleLang}
              title={t.toggleLang}
            >
              {lang === "en" ? "中" : "EN"}
            </button>
            <button
              className="icon-btn"
              onClick={toggleTheme}
              aria-label={t.toggleTheme}
              title={t.toggleTheme}
            >
              {theme === "dark" ? Icon.sun : Icon.moon}
            </button>
            <button
              className={"icon-btn" + (view === "list" ? " active" : "")}
              onClick={() => setView(view === "grid" ? "list" : "grid")}
              aria-label={view === "grid" ? t.viewList : t.viewGrid}
              aria-pressed={view === "list"}
              title={view === "grid" ? t.viewList : t.viewGrid}
            >
              {view === "grid" ? Icon.list : Icon.grid}
            </button>
          </div>
          <div className="filters" role="tablist" aria-label="分类筛选">
            {catList.map((c) => (
              <button
                key={c.name}
                type="button"
                role="tab"
                aria-selected={c.name === activeCat}
                className={"chip" + (c.name === activeCat ? " active" : "")}
                onClick={() => setActiveCat(c.name)}
              >
                {catName(c.name)}
                <span className="count">{c.count}</span>
              </button>
            ))}
          </div>
        </section>

        <section className="result-count" aria-live="polite">
          <span>
            {t.showing} {filtered.length} {t.of} {skills.length} {t.skillsUnit}
          </span>
          {(activeCat !== "全部" || query.trim()) && (
            <button
              type="button"
              className="clear-btn"
              onClick={() => { setActiveCat("全部"); setQuery(""); }}
            >
              {t.clear}
            </button>
          )}
        </section>

        <section className={"grid " + view} aria-label="技能列表">
          {filtered.map((s) => (
            <article
              key={s.dir}
              className="card"
              role="button"
              tabIndex={0}
              aria-label={`${lang === "en" ? "View details for skill" : "查看技能"} ${s.name}`}
              onClick={() => openModal(s)}
              onKeyDown={(e) => {
                if (e.key === "Enter" || e.key === " ") {
                  e.preventDefault();
                  openModal(s);
                }
              }}
            >
              <div className="card-cat">{catName(s.category)}</div>
              <h3 className="card-name">{s.name}</h3>
              {s.en_name && s.en_name !== s.name && (
                <div className="card-alias">{s.en_name}</div>
              )}
              <p className="card-desc">
                {lang === "en" ? s.en_desc || s.zh_desc : s.zh_desc || s.en_desc}
              </p>
              <div className="card-foot">{tagHtml(s)}</div>
            </article>
          ))}
        </section>

        {filtered.length === 0 && (
          <div className="empty" role="status">
            {Icon.empty}
            <p><strong>{t.emptyTitle}</strong></p>
            <p>{t.emptyDesc}</p>
          </div>
        )}
      </main>

      <footer className="footer">
        <p>
          {t.maintained}
          {meta.count}
          {t.by}
          {meta.author || (lang === "en" ? "community" : "社区")}
          {t.maintainedBy}
          {(meta.generated_at || "").slice(0, 10)}
        </p>
        <p className="muted">
          {lang === "en" ? "This page is the " : "本页面为 "}
          <a href={meta.repo} target="_blank" rel="noopener">Agent Skills Hub</a>
          {" "}
          {t.footerNote}
          <code>build_site.py</code>
          {t.footerNote2}
        </p>
      </footer>

      {modal && (
        <div className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title">
          <div className="modal-backdrop" onClick={closeModal} />
          <div className="modal-card">
            <button className="modal-close" onClick={closeModal} aria-label={t.close}>
              ×
            </button>
            <div className="modal-cat">{catName(modal.category)}</div>
            <h2 id="modal-title">{modal.name}</h2>
            {modal.en_name && modal.en_name !== modal.name && (
              <div className="modal-alias">{modal.en_name}</div>
            )}
            <p className="modal-desc">
              {lang === "en" ? modal.en_desc || modal.zh_desc : modal.zh_desc || modal.en_desc}
            </p>
            <div className="modal-tags">{tagHtml(modal)}</div>
            <a
              className="btn btn-primary"
              target="_blank"
              rel="noopener"
              href={`${repoBase}/tree/main/skills/${encodeURIComponent(modal.dir)}/SKILL.md`}
            >
              {t.viewSkill}
            </a>
          </div>
        </div>
      )}
    </>
  );
}
