import { readFileSync } from "node:fs";
const ROOT = "e:/Github/Agent-Skills-Hub";
const d = JSON.parse(readFileSync(ROOT + "/data/skills-data.json", "utf8"));
const c = {};
d.skills.forEach((s) => { c[s.category] = (c[s.category] || 0) + 1; });
console.log("DATA_CATEGORIES:", JSON.stringify(c));
const tax = readFileSync(ROOT + "/tools/lib/taxonomy.mjs", "utf8");
const m = tax.match(/CATEGORY_ORDER\s*=\s*\[([\s\S]*?)\]/);
const arr = m ? m[1].split(",").map((x) => x.trim()).filter(Boolean).map((x) => x.replace(/['"`]/g, "")) : [];
console.log("TAXONOMY_COUNT:", arr.length, "TAXONOMY:", JSON.stringify(arr));
const diff = arr.filter((x) => !Object.keys(c).includes(x));
console.log("DATA_NOT_IN_TAXONOMY:", JSON.stringify(diff));
const extra = Object.keys(c).filter((x) => !arr.includes(x));
console.log("DATA_EXTRA:", JSON.stringify(extra));
