// 路径: site/app/Showcase.jsx 版本: 1.0.0
"use client";

import { useEffect, useMemo, useState, useCallback } from "react";

// 界面文案双语映射
const UI = {
  zh: {
    all: "全部",
    skillsUnit: "个技能",
    catsUnit: "个分类",
    viewRepo: "查看 GitHub 仓库",
    install: "用 skills-manager 安装",
    searchPh: "搜索技能名称、描述或分类…",
    searchLabel: "搜索技能",
    toggleTheme: "切换深色 / 浅色主题",
    toggleLang: "Switch to English",
    clear: "清除筛选",
    showing: "显示",
    of: "/",
    empty: "没有匹配的技能，换个关键词试试。",
    maintained: "共 ",
    by: " 个技能 · 由 ",
    maintainedBy: " 维护 · 生成于 ",
    footerNote: " 的静态展示，由 Next.js 构建、",
    footerNote2: " 自动生成数据。许可证：MIT。",
    viewSkill: "在仓库中查看 SKILL.md →",
    close: "关闭",
    subtitle: "面向开发、设计、测试、DevOps、Agent 工程及各行业领域的 AI 技能集合",
  },
  en: {
    all: "All",
    skillsUnit: "skills",
    catsUnit: "categories",
    viewRepo: "View GitHub Repository",
    install: "Install with skills-manager",
    searchPh: "Search by name, description or category…",
    searchLabel: "Search skills",
    toggleTheme: "Toggle dark / light theme",
    toggleLang: "切换到中文",
    clear: "Clear filters",
    showing: "Showing",
    of: " / ",
    empty: "No matching skills. Try another keyword.",
    maintained: "Total ",
    by: " skills · maintained by ",
    maintainedBy: " · generated on ",
    footerNote: " static showcase, built with Next.js and generated by ",
    footerNote2: ". License: MIT.",
    viewSkill: "View SKILL.md in repo →",
    close: "Close",
    subtitle:
      "A collection of AI skills for development, design, testing, DevOps, agent engineering and industry domains",
  },
};

export default function Showcase({ data }) {
  const { meta, categories, skills } = data;
  const [activeCat, setActiveCat] = useState("全部");
  const [query, setQuery] = useState("");
  const [modal, setModal] = useState(null);
  const [theme, setTheme] = useState("light");
  const [lang, setLang] = useState(() => {
    if (typeof document === "undefined") return "zh";
    const stored = document.documentElement.getAttribute("data-lang");
    if (stored === "en" || stored === "zh") return stored;
    return (navigator.language || "").toLowerCase().startsWith("en") ? "en" : "zh";
  });

  useEffect(() => {
    const cur =
      document.documentElement.getAttribute("data-theme") ||
      (window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light");
    setTheme(cur);
  }, []);

  const toggleTheme = () => {
    const next = theme === "dark" ? "light" : "dark";
    setTheme(next);
    document.documentElement.setAttribute("data-theme", next);
    try {
      localStorage.setItem("theme", next);
    } catch (e) {
      /* 忽略存储异常 */
    }
  };

  const toggleLang = () => {
    const next = lang === "en" ? "zh" : "en";
    setLang(next);
    document.documentElement.setAttribute("data-lang", next);
    document.documentElement.lang = next === "en" ? "en" : "zh-CN";
    try {
      localStorage.setItem("lang", next);
    } catch (e) {
      /* 忽略存储异常 */
    }
  };

  const t = UI[lang];
  // 分类英文名从数据读取，新增分类无需修改前端代码
  const catEnMap = useMemo(
    () =>
      Object.fromEntries(
        (data.categories || []).map((c) => [c.name, c.en || c.name])
      ),
    [data.categories]
  );
  const catName = (name) => (lang === "en" ? catEnMap[name] || name : name);

  const catList = useMemo(
    () => [{ name: "全部", count: skills.length }].concat(categories),
    [categories, skills.length]
  );

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    return skills.filter((s) => {
      if (activeCat !== "全部" && s.category !== activeCat) return false;
      if (!q) return true;
      const hay = [s.name, s.zh_desc, s.en_desc, s.category].join(" ").toLowerCase();
      return hay.indexOf(q) !== -1;
    });
  }, [skills, activeCat, query]);

  const openModal = useCallback((s) => setModal(s), []);
  const closeModal = useCallback(() => setModal(null), []);

  useEffect(() => {
    if (!modal) return;
    const onKey = (e) => {
      if (e.key === "Escape") closeModal();
    };
    document.addEventListener("keydown", onKey);
    document.body.style.overflow = "hidden";
    return () => {
      document.removeEventListener("keydown", onKey);
      document.body.style.overflow = "";
    };
  }, [modal, closeModal]);

  const tagHtml = (s) => (
    <>
      <span className={"tag" + (s.has_scripts ? " has" : "")}>scripts</span>
      <span className={"tag" + (s.has_references ? " has" : "")}>references</span>
      <span className={"tag" + (s.has_assets ? " has" : "")}>assets</span>
    </>
  );

  const repoBase = (meta.repo || "").replace(/\/$/, "");

  return (
    <>
      <header className="hero" id="hero">
        <div className="hero-inner" id="hero-inner">
          <div className="badge">AGENT SKILLS HUB</div>
          <h1>{meta.title}</h1>
          <p className="subtitle">{t.subtitle}</p>
          <div className="stats" id="stats">
            <div className="stat">
              <div className="stat-num">{meta.count}</div>
              <div className="stat-label">{t.skillsUnit}</div>
            </div>
            <div className="stat">
              <div className="stat-num">{categories.length}</div>
              <div className="stat-label">{t.catsUnit}</div>
            </div>
          </div>
          <div className="cta" id="cta">
            <a className="btn btn-primary" href={meta.repo} target="_blank" rel="noopener">
              {t.viewRepo}
            </a>
            <a
              className="btn btn-ghost"
              href="https://github.com/xingkongliang/skills-manager"
              target="_blank"
              rel="noopener"
            >
              {t.install}
            </a>
          </div>
        </div>
        <div className="hero-glow" aria-hidden="true" />
      </header>

      <main className="container" id="main">
        <section className="toolbar" id="toolbar">
          <div className="toolbar-top" id="toolbar-top">
            <div className="search-wrap" id="search-wrap">
              <svg className="search-icon" viewBox="0 0 24 24" width="18" height="18" aria-hidden="true">
                <path
                  fill="currentColor"
                  d="M15.5 14h-.79l-.28-.27a6.5 6.5 0 1 0-.7.7l.27.28v.79l5 4.99L20.49 19l-4.99-5Zm-6 0A4.5 4.5 0 1 1 14 9.5 4.5 4.5 0 0 1 9.5 14Z"
                />
              </svg>
              <input
                id="search"
                type="search"
                placeholder={t.searchPh}
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                autoComplete="off"
                aria-label={t.searchLabel}
              />
            </div>
            <button
              className="lang-toggle"
              onClick={toggleLang}
              aria-label={t.toggleLang}
              title={t.toggleLang}
            >
              {lang === "en" ? "中" : "EN"}
            </button>
            <button
              className="theme-toggle"
              onClick={toggleTheme}
              aria-label={t.toggleTheme}
              title={t.toggleTheme}
            >
              {theme === "dark" ? (
                <svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                  <circle cx="12" cy="12" r="4" />
                  <path d="M12 2v2M12 20v2M2 12h2M20 12h2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4" />
                </svg>
              ) : (
                <svg viewBox="0 0 24 24" width="20" height="20" fill="currentColor" aria-hidden="true">
                  <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79Z" />
                </svg>
              )}
            </button>
          </div>
          <div className="filters" id="filters">
            {catList.map((c) => (
              <button
                key={c.name}
                type="button"
                className={"chip" + (c.name === activeCat ? " active" : "")}
                aria-pressed={c.name === activeCat}
                onClick={() => setActiveCat(c.name)}
              >
                {catName(c.name)}
                <span className="count">{c.count}</span>
              </button>
            ))}
          </div>
        </section>

        <section className="result-count" id="result-count">
          <span>
            {t.showing} {filtered.length} {t.of} {skills.length} {t.skillsUnit}
          </span>
          {(activeCat !== "全部" || query.trim()) && (
            <button
              type="button"
              className="clear-btn"
              onClick={() => {
                setActiveCat("全部");
                setQuery("");
              }}
            >
              {t.clear}
            </button>
          )}
        </section>

        <section className="grid" id="grid">
          {filtered.map((s) => (
            <article
              key={s.dir}
              id={"card-" + s.dir}
              className="card"
              role="button"
              tabIndex={0}
              aria-label={`${lang === "en" ? "View details for skill" : "查看技能"} ${s.name}`}
              onClick={() => openModal(s)}
              onKeyDown={(e) => {
                if (e.key === "Enter" || e.key === " ") {
                  e.preventDefault();
                  openModal(s);
                }
              }}
            >
              <div className="card-cat">{catName(s.category)}</div>
              <h3 className="card-name">{s.name}</h3>
              <p className="card-desc">
                {lang === "en" ? s.en_desc || s.zh_desc : s.zh_desc || s.en_desc}
              </p>
              <div className="card-foot">{tagHtml(s)}</div>
            </article>
          ))}
        </section>
        {filtered.length === 0 && (
          <p className="empty">{t.empty}</p>
        )}
      </main>

      <footer className="footer" id="footer">
        <p>
          {t.maintained}
          {meta.count}
          {t.by}
          {meta.author || (lang === "en" ? "community" : "社区")}
          {t.maintainedBy}
          {(meta.generated_at || "").slice(0, 10)}
        </p>
        <p className="muted">
          {lang === "en" ? "This page is the " : "本页面为 "}
          <a href={meta.repo} target="_blank" rel="noopener">Agent Skills Hub</a>
          {" "}
          {t.footerNote}
          <code>build_site.py</code>
          {t.footerNote2}
        </p>
      </footer>

      {modal && (
        <div className="modal" id="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title">
          <div className="modal-backdrop" onClick={closeModal} />
          <div className="modal-card" id="modal-card">
            <button className="modal-close" onClick={closeModal} aria-label={t.close}>
              ×
            </button>
            <div className="modal-cat">{catName(modal.category)}</div>
            <h2 id="modal-title">{modal.name}</h2>
            <p className="modal-desc">
              {lang === "en" ? modal.en_desc || modal.zh_desc : modal.zh_desc || modal.en_desc}
            </p>
            <div className="modal-tags">{tagHtml(modal)}</div>
            <a
              className="btn btn-primary"
              target="_blank"
              rel="noopener"
              href={`${repoBase}/tree/main/skills/${encodeURIComponent(modal.dir)}/SKILL.md`}
            >
              {t.viewSkill}
            </a>
          </div>
        </div>
      )}
    </>
  );
}
